import { Nav } from "../components/layout/Nav";
import Image from "next/image";
import Head from "next/head";
import { Icon } from "@iconify/react";

import { useState } from "react";
import { Tabs } from "@mantine/core";

export const getStaticProps = async () => {
  const res = await fetch("http://localhost:1337/hotels");
  const data = await res.json();

  return {
    props: { hotel: data },
  };
};

const Admin = ({ hotel, id }) => {
  const [activeTab, setActiveTab] = useState(1);

  return (
    <div key={id}>
      <Head>
        <title>Holidaze</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="admin-header">
        <Nav />
      </header>

      <div className="admin">
        <h1 className="admin__headline">Admin</h1>

        <div>
          <Tabs
            color="dark"
            variant="pills"
            tabPadding="lg"
            active={activeTab}
            onTabChange={setActiveTab}
          >
            <Tabs.Tab label="Hotels">
              <div key={id} className="admin__wrapper">
                <table className="table-auto admin__table">
                  <thead>
                    <tr>
                      <th className="admin__th">ID</th>
                      <th className="admin__th">Hotels</th>
                      <th className="admin__th">Image</th>
                      <th className="admin__th">Description</th>
                      <th className="admin__th">Price</th>
                      <th className="admin__th">Amenities</th>
                      <th className="admin__th">Location</th>
                      <th className="admin__th">Edit</th>
                      <th className="admin__th">Delete</th>
                    </tr>
                  </thead>
                  <>
                    <tbody>
                      {hotel.map(
                        ({
                          id,
                          name,
                          short_description,
                          // stars,
                          featured_img,
                          price,
                          amenities,
                          // free_cancellation,
                          location,
                        }) => {
                          return (
                            <tr key={id}>
                              <td className="admin__td">{id}</td>
                              <td className="admin__td">{name}</td>
                              <td className="admin__td">
                                <img
                                  alt=""
                                  src={featured_img}
                                  height={400}
                                  width={400}
                                ></img>
                              </td>
                              <td className="admin__td">{short_description}</td>
                              <td className="admin__td">{price}</td>
                              <td className="admin__td">{amenities}</td>
                              <td className="admin__td">{location}</td>
                              <td className="admin__td">
                                <Icon
                                  icon="akar-icons:edit"
                                  color="#1d282e"
                                  height={20}
                                />
                              </td>
                              <td className="admin__td">
                                <Icon
                                  icon="cil:trash"
                                  color="#1d282e"
                                  height={20}
                                />
                              </td>
                            </tr>
                          );
                        }
                      )}
                    </tbody>
                  </>
                </table>
                ;
              </div>
            </Tabs.Tab>
            <Tabs.Tab label="Enquiries">Settings tab content</Tabs.Tab>
            <Tabs.Tab label="Messages">Messages tab content</Tabs.Tab>
          </Tabs>
        </div>

        {/* 
        <div className="admin__btn-right">
          <button className="admin__btn">Add Hotels</button>
        </div> */}
      </div>
    </div>
  );
};

export default Admin;
