import { Nav } from "../components/layout/Nav";
import Image from "next/image";
import Head from "next/head";

export const getStaticProps = async () => {
  const res = await fetch("http://localhost:1337/hotels");
  const data = await res.json();

  return {
    props: { hotel: data },
  };
};

const Admin = ({ hotel, id }) => {
  return (
    <div key={id}>
      <Head>
        <title>Holidaze</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="admin-header">
        <Nav />
      </header>

      <div className="admin">
        <h1 className="admin__headline">Admin</h1>
        <div className="admin__btn-div">
          <div className="admin__btn-inner">
            <button className="admin__btn admin__active">Hotels</button>
            <button className="admin__btn">Enquiries</button>
            <button className="admin__btn">Message</button>
          </div>
          <div className="admin__btn-right">
            <button className="admin__btn">Add Hotels</button>
          </div>
        </div>

        <div className="">
          {hotel.map(
            ({
              id,
              name,
              short_description,
              stars,
              featured_img,
              price,
              amenities,
              free_cancellation,
              location,
            }) => {
              return (
                <div key={id} className="admin__wrapper">
                  {/* <table className="admin__table">
                    <td>{id}</td>

                    <td>{name}</td>

                    <td>
                      <img
                        src={featured_img}
                        alt="Image of hotelroom"
                        width={50}
                        height={50}
                      ></img>
                    </td>

                    <td>{short_description}</td>

                    <td>{price}</td>
                    <td>{location}</td>
                  </table> */}
                </div>
              );
            }
          )}
        </div>
      </div>
    </div>
  );
};

export default Admin;
