import Head from "next/head";
import Nav from "../components/layout/Nav";
import SocialMediaIcons from "../components/icons/SocialMediaIcons";

export default function Contact() {
  return (
    <div className="bg-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <h1 title="Contact Holidaze"></h1>
      <p>
        The chat is the fastest way to talk to one of our Customer Service
        agents about your bookings.
      </p>
      <div>
        <p>You can also call us: + 47 000 10 200</p>
      </div>
      <div>
        <h3>Find us on social media</h3>
        <SocialMediaIcons />
      </div>
    </div>
  );
}
