import Head from "next/head";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import Attractions from "../components/attractions/Attractions";
import Newsletter from "../components/newsletter/Newsletter";
import IconsHomePage from "../components/icons/IconsHomePage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Holidaze</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        <div className="home">
          <h1>Why use Holidaze for your booking?</h1>
          <IconsHomePage />
          <div className="home__section-1">
            <h3>
              Free cancellation
              <span className="block">on most of the hotels*</span>
            </h3>
            <h3>15% Bonus</h3>
            <h3>Safe payment</h3>
            <h3>24/7 chat</h3>
          </div>
        </div>

        <Attractions />
        <Newsletter />
      </main>
      <Footer />
    </>
  );
}
