import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "../components/nav/Nav";
import HeroImage from "../components/hero/HeroImage";
import HeroText from "../components/hero/HeroText";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroImage>
        <Nav />
        <HeroText />
      </HeroImage>

      <footer className={styles.footer}></footer>
    </div>
  );
}
