import Head from "next/head";
import Nav from "../components/layout/Nav";
import Searchbar from "../components/searchbar/Searchbar";

export default function Stays() {
  return (
    <div className="bg-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className="stays">
        <section>
          <div className="ml-12 mt-10">
            <h3 className=" white__text">Good day,</h3>
            <h1>Find the best place for you to stay</h1>
          </div>
          <div className="searchbar__stays">
            <Searchbar className="pt-10" />
          </div>
        </section>
      </main>
    </div>
  );
}
